version: "3.7"
services:
  redis:
    image: redis
    command: redis-server --requirepass 1234 --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: PLUG
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: PLUG